### ISSUE TITLE
Add instructions in readme for installing into DT

### ISSUE THREAD

**Issue by PProvost** [jade-nl/dt.styles#5]
It isn't clear from the readme how to actually install this into darktable to get the hierarchical view you mentioned. I tried unzipping it into the styles folder where I found the styles that I'd created (on Windows it was `%USERPROFILE%/darktable/styles`), but nothing showed up in DT after I restarted it.

Suggestions?

**Comment by jade-nl** [comment]
Hi,

Use the *Import* function as mentioned in the [darktable user manual](https://darktable-org.github.io/dtdocs/en/module-reference/utility-modules/lighttable/styles/)

---

Here's a step-by-step

* in lighttable open the styles module and click on *import*
![01](https://user-images.githubusercontent.com/56407344/175762907-54534db7-41d8-4ffc-924c-7b734aedb229.png)

* in the following menu traverse to the dir/folder that holds the downloaded style(s)
![03](https://user-images.githubusercontent.com/56407344/175762988-6a5e3de3-4472-4d7e-830d-5b86809ce62b.png)

Too my knowledge you cannot import a complete directory/sub-directory structure (as in: select all the sub-directories that are in Styles), so you need to do this for each section.

They now show up in the styles module in a hierarchical form:
![04a](https://user-images.githubusercontent.com/56407344/175763037-618b54b6-a150-476c-aebc-b53fc768dbf4.png)

And in darktroom they show in a simpler form:

![4b](https://user-images.githubusercontent.com/56407344/175763077-0ba4394b-565b-4a75-80b6-4647551e91af.png)
